class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
init_args:
  dirpath: checkpoints/sentinel-src-mqm-lin
  filename: '{epoch}-{step}-{val_mse_loss:.5f}'
  monitor: val_mse_loss
  verbose: True
  save_last: True
  save_top_k: 2
  mode: min
  auto_insert_metric_name: True
  save_weights_only: True
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 1
  save_on_train_epoch_end: null
